name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '16' ]
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
    - name: print Java version
      run: java -version
    - name: Build with Gradle
      run: ./gradlew build

  automerge:
    runs-on: [ubuntu-latest]
    name: automerge
    needs: [build]
    if: github.base_ref == 'main' && github.actor == 'dependabot[bot]'
    steps:
    - name: merge
      uses: actions/github-script@v4.0.2
      with:
        script: |
          github.pulls.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number,
            merge_method: 'squash'
          })
        github-token: ${{secrets.GITHUB_TOKEN}}
